#!/usr/bin/env python3
###############################################################
# SPDX-License-Identifier: BSD-2-Clause-Patent
# SPDX-FileCopyrightText: 2022 the prplMesh contributors (see AUTHORS.md)
# This code is subject to the terms of the BSD+Patent license.
# See LICENSE file for more details.
###############################################################

import sys
import subprocess
import re
import datetime
import argparse
import textwrap

generation_datetime = datetime.datetime.now().isoformat(sep=' ', timespec='minutes')
args = ""
preamble_commit = "profiles: prpl: prplMesh: bump to {}-{}"\
                  "\n\nIntegrates following changes:"

preamble = f"""\
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

Note that this file is generated by the script `{sys.argv[0]}`,
which can be found in the prplMesh repository.
Please do not edit this file by hand, simply re-run the script.

Generated on {generation_datetime}

"""


def insert_item(commithash: str, itemtype: str, descr: str, jira: str, items: list):
    changes = []
    for change in items:
        changes.append(change[2])

    # only add if the change isn't a duplicate
    if descr not in changes:
        items += [(commithash, itemtype, descr, jira)]


def get_branchname(githash: str):
    branchname = subprocess.run(['git', 'rev-parse', '--abbrev-ref', githash],
                                capture_output=True,
                                text=True).stdout
    return branchname.strip()


def get_commitdate(githash: str):
    date = subprocess.run(['git', 'show', '--no-patch', '--format=%cs', githash],
                          capture_output=True,
                          text=True).stdout
    return date.strip()


def parse_merge_commit(logline: str, items: list):
    # ... look for merge commits that merge a bugfix, feature or hotfix branch ...
    item = re.match("([0-9a-f]+) Merge branch '(bugfix|feature|dev)/(PPM-\\d+|PPM_\\d+|PPW-\\d+|PPW_\\d+|PCF-\\d+|PCF_\\d+)", logline) # noqa E501 # pylint: disable=line-too-long
    if not item:
        item = re.match("([0-9a-f]+) Merge branch '(hotfix)/", logline)
    if item:
        # ... extract the hash, type (bugfix, feature, hotfix) and JIRA from it ...
        githash = item.group(1)
        itemtype = item.group(2).title()
        jira = item.group(3) if len(item.groups()) > 2 else ''
        # ... use the hash to obtain the full description text ...
        change_desc = subprocess.run(['git', 'show', '--format=%b', '-s', githash],
                                     capture_output=True,
                                     text=True).stdout
        # ... only add the first line, and sanitize it for inclusion in markdown ...
        change = change_desc.split('\n')[0].strip()
        bad_char = r"\*_()[]<>{}!@#$%^&~|"
        if not args.bump_commit:
            for c in bad_char:
                change = change.replace(c, '\\'+c)
        # Purge merges with empty descriptions
        if change:
            insert_item(githash, itemtype, change, jira, items)


def get_log_entry(current_version: str, prev_version: str):
    items = []
    version_filter = f"{prev_version}..{current_version}" if prev_version else current_version
    # For each 'git log' line between the two versions ...
    with subprocess.Popen(["git", "log", "--oneline", "--merges", version_filter],
                          stdout=subprocess.PIPE,
                          universal_newlines=True) as log:
        for line in log.stdout.readlines():
            parse_merge_commit(line, items)

    with subprocess.Popen(["git", "log", "--oneline", "--no-merges", version_filter],
                          stdout=subprocess.PIPE,
                          universal_newlines=True) as log:
        for line in log.stdout.readlines():
            # Go over all non-merge commits
            commit = re.match("([0-9a-f]+)", line)
            if not commit:
                continue

            # Try to look into the commit description if this commit is cherry-picked
            commit_desc = subprocess.run(['git', 'show', '--format=%b', '-s', commit.group(1)],
                                         capture_output=True,
                                         text=True).stdout
            cherry_picked_from = re.search(r"\(cherry picked from commit ([0-9a-f]+)\)",
                                           commit_desc)

            if cherry_picked_from:
                gitlog = subprocess.Popen((['git', 'log', cherry_picked_from.group(1)+'..master',
                                          '--ancestry-path', '--merges', '--oneline']),
                                          stderr=subprocess.PIPE,
                                          stdout=subprocess.PIPE)
                mergecommit = subprocess.check_output(('tail', '-1'),
                                                      stdin=gitlog.stdout,
                                                      text=True)
                gitlog.wait()

                mergecommithash = re.match("([0-9a-f]+)", mergecommit)
                if mergecommithash:
                    parse_merge_commit(mergecommit, items)

    return items


def main():
    parser = argparse.ArgumentParser(prog=sys.argv[0],
                                     description="Generate a changelog in Markdown format.")
    parser.add_argument('-s', '--start-version', type=str, default=None,
                        help="Display the changelog since this version")
    parser.add_argument('-l', '--latest-version', action='store_true',
                        help="Only show the changes in the latest version (since latest-1)")
    parser.add_argument('-b', '--bump-commit', type=str, default=None,
                        help="Generate a bump commit description (since specified commit)")
    parser.add_argument('-P', '--no-preamble', action='store_true',
                        help="Disable the preamble, just print the raw changelog")
    parser.add_argument('-U', '--no-unreleased', action='store_true',
                        help="By default, we start with 'unreleased' changes."
                             "This option suppresses that.")
    global args
    args = parser.parse_args()

    # Get all tags in logical order, remove ones that are not releases (x.y.z)
    tags = subprocess.run(['git', 'tag', '--merged', get_branchname("HEAD")],
                          capture_output=True, text=True).stdout
    versions = [tag for tag in tags.split('\n') if re.match(r'^\d+.\d+.\d+$', tag)]

    if args.start_version and args.latest_version:
        raise argparse.ArgumentError('-s', "-s and -l are mutually exclusive options!")
    if args.bump_commit and (args.start_version or args.latest_version or args.no_unreleased):
        raise argparse.ArgumentError('-b', "-b cannot be used with any other option!")
    if args.latest_version:
        versions = versions[-2:]
    if args.start_version and args.start_version not in versions:
        raise argparse.ArgumentError('-s', f"{args.start_version} is not a valid version!"
                                           f"Must be one of: {str(versions)}")
    if args.start_version:
        versions = versions[versions.index(args.start_version):]
    if not args.no_unreleased:
        # Pretend 'HEAD' is also a version, so we can get stats about unreleased changes from git
        versions.append('HEAD')

    prev = None
    output = []

    if args.bump_commit:
        print(preamble_commit.format(get_branchname("HEAD"), get_commitdate("HEAD")))
        changes = get_log_entry("HEAD", args.bump_commit)
        jiras = "\n\n"
        for c in changes:
            print("- {} ({})".format(c[2], c[0]))
            if c[3]:
                jiras += "{}, ".format(c[3])
        print()

        # Clean up and wrap the jira list
        jiras = jiras.rstrip(', ')
        references_list = textwrap.wrap(text=jiras, width=75,
                                        initial_indent='References:',
                                        subsequent_indent='             ')

        for reference_line in references_list:
            print(reference_line)

    else:
        for version in versions:
            # Skip the first version, since otherwise we would list ALL changes
            # before the first selected version as belonging to that version, which is usually wrong
            if version == versions[0]:
                prev = version
                continue

            release_date = subprocess.run(
                                ['git', 'tag', '-l', '--format=%(taggerdate:iso8601)', version],
                                capture_output=True,
                                text=True).stdout
            o = f"\n## [{version}]"\
                f"(https://gitlab.com/prpl-foundation/prplmesh/prplMesh/-/releases/{version})"\
                f" - {release_date}\n"\
                if version != "HEAD" else "## Unreleased\n"
            changes = get_log_entry(version, prev)
            bugs = [c for c in changes if c[1] in ('Bugfix', 'Hotfix')]
            features = [c for c in changes if c[1] == 'Feature']

            o += "\n### Changed\n\n"
            for f in features:
                o += "- [{}]({})\n".format(
                        f[2],
                        'https://prplfoundationcloud.atlassian.net/browse/' + f[3])

            o += "\n### Fixed\n\n"
            for b in bugs:
                if b[2]:
                    o += "- [{}]({})\n".format(
                            b[2],
                            'https://prplfoundationcloud.atlassian.net/browse/' + b[3])
                else:
                    o += "- {}\n".format(b[1])

            output.append(o)
            prev = version

        if not args.no_preamble:
            print(preamble)
        print('\n'.join(reversed(output)))


main()
